services:
  mongo4.falseendless.cn:
    image: docker.xuanyuan.me/bitnami/mongodb-sharded:8.0
    hostname: mongo4.falseendless.cn  #换成你的域名
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongo4.falseendless.cn  #换成你的域名
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=${MONGO_PASSWORD:-} #换成你的密码
      - MONGODB_REPLICA_SET_KEY=falseendless
      - MONGODB_REPLICA_SET_NAME=rs1
      - BITNAMI_DEBUG=true
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_MONGOS_HOST=mongos.falseendless.cn  #换成你的域名
      - MONGODB_MONGOS_PORT_NUMBER=27071
      - MONGODB_CFG_PRIMARY_PORT_NUMBER=27072
    volumes:
      - /www/server/mongo7/primary:/bitnami/mongodb  #换成你的本地挂载地址

  mongo2.falseendless.cn:
    image: docker.xuanyuan.me/bitnami/mongodb-sharded:8.0
    hostname: mongo2.falseendless.cn  #换成你的域名
    restart: always
    ports:
      - "27018:27018"
    environment:
      - MONGODB_PORT_NUMBER=27018
      - MONGODB_ADVERTISED_PORT_NUMBER=27018
      - MONGODB_ADVERTISED_HOSTNAME=mongo2.falseendless.cn  #换成你的域名
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongo1.falseendless.cn  #换成你的域名
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_USER=root
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=${MONGO_PASSWORD:-}  #换成你的密码
      - MONGODB_REPLICA_SET_KEY=falseendless
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_MONGOS_HOST=mongos.falseendless.cn  #换成你的域名
      - MONGODB_MONGOS_PORT_NUMBER=27071
      - MONGODB_CFG_PRIMARY_PORT_NUMBER=27072

  mongo3.falseendless.cn:
    image: docker.xuanyuan.me/bitnami/mongodb-sharded:8.0
    hostname: mongo3.falseendless.cn  #换成你的域名
    restart: always
    ports:
      - "27019:27019"
    environment:
      - MONGODB_PORT_NUMBER=27019
      - MONGODB_ADVERTISED_PORT_NUMBER=27019
      - MONGODB_ADVERTISED_HOSTNAME=mongo3.falseendless.cn  #换成你的域名
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongo1.falseendless.cn  #换成你的域名
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_USER=root
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=${MONGO_PASSWORD:-}  #换成你的密码
      - MONGODB_REPLICA_SET_KEY=falseendless
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_MONGOS_HOST=mongos.falseendless.cn  #换成你的域名
      - MONGODB_MONGOS_PORT_NUMBER=27071
      - MONGODB_CFG_PRIMARY_PORT_NUMBER=27072
